### ISSUE TITLE
Use icons generated by FaviconsWebpackPlugin in manifest?

### ISSUE THREAD

**Issue by nealoke** [arthurbergmz/webpack-pwa-manifest#22]
Hi! Currently I'm creating icons twice which seems a bit wrong to me. Is it possible to include the icons generated by [`FaviconsWebpackPlugin`](https://github.com/jantimon/favicons-webpack-plugin) inside the `manifest.json` file?

**Comment by arthurbergmz** [comment]
Unfortunatelly, I see no ways of doing that automatically, since `WebpackPwaManifest` and `FaviconsWebpackPlugin` have their own way of producing icons. I need the icons to be generated before the manifest itself, so I can create a fingerprint of it. Even if `FaviconsWebpackPlugin` ran and produced their icons before `WebpackPwaManifest`, I can't think a way, right now, of retrieving those files.

I'll keep this issue open if anyone have an idea of doing that.

**Comment by dangodev** [comment]
I know webpack provides hooks for assets produced by webpack with the `stats` callback for plugin hooks (see https://github.com/soundcloud/chunk-manifest-webpack-plugin/issues/6#issuecomment-153367017 as an example). I’m speaking a little beyond my depth here but is there any reason why webpack-pwa-manifest must bypass this?

Encountering the same issue and don’t know how to solve it. I need this for iOS, but I’m not using the HTML webpack plugin so the `ios: true` flag won’t work for me.

**Comment by ciampo** [comment]
+1 on @dangodev comment.

It would be really good it this plugin somehow exposed to webpack and the rest of the plugins all the stats of the files being generated (i.e., the manifest file and all the icons).

This is particularly useful when setting `inject: false`

**Comment by arthurbergmz** [comment]
**v4.0.0** will have default support for favicons.
