### ISSUE TITLE
Emit file

### ISSUE THREAD

**Issue by eliseumds** [arthurbergmz/webpack-pwa-manifest#27]
Does this plugin emit the generated `manifest.json`? This way I could read it from my `stats.json` and include it in the HTML source (we're using React instead of HtmlWebpackPlugin).

Thanks for the great work!

**Comment by eliseumds** [comment]
Oh, the plugins emits the files but without a chunk name. Because of that, `webpack-manifest-plugin` doesn't catch them. Has anyone been through that?

**Comment by arthurbergmz** [comment]
Can you explain what's going on and what do you want to achieve, please?

Maybe we can work on that.

**Comment by arthurbergmz** [comment]
I'm closing this ticket since the author didn't give the information needed in more than a month.

**Comment by eike-hass** [comment]
I face a similar issue. I would like to reference the generated manifest from the output of https://github.com/ztoben/assets-webpack-plugin. The key in the generated asset manifest (from the assets-plugin) is simply `""`. I assume because there is no chunck name. Would it be possible to add a setting to specify that in the config?
