### ISSUE TITLE
ERROR in   TypeError: supportedMimeTypes.includes is not a function

### ISSUE THREAD

**Issue by mkitzman** [arthurbergmz/webpack-pwa-manifest#55]
Hi,

This is probably just something I am doing wrong or the version of webpack I'm using but I thought I would report this just in case:

When adding icons to the config and building webpack the icons aren't created due to this error:

```
ERROR in   TypeError: supportedMimeTypes.includes is not a function
  - index.js:117 process
    [mk2]/[webpack-pwa-manifest]/dist/icons/index.js:114:29
```

I am using 
```
"webpack": "^3.10.0",
"webpack-pwa-manifest": "^3.6.2"
```

My config object is

   ```
 new WebpackPwaManifest({
        name: 'Name',
        short_name: 'CoolName',
        description: 'MySite',
        background_color: '#FFFFFF',
        inject: true,
        ios: true,
        icons: [
            {
                src: './src/images/icon.png',
                sizes: [96, 128, 192],
                ios: true
            }
        ]
    })
```

Changing line 114 in ```webpack-pwa-manifest]/dist/icons/index.js``` from 

```if (!supportedMimeTypes.includes(mimeType)) {```

to

```if (supportedMimeTypes.indexOf(mimeType) === -1) {```

fixes the issue and icons generate fine.

**Comment by cvan** [comment]
@mkitzman which version of Node.js are you running (`node --version`)?

**Comment by doug-wade** [comment]
I suspect @cvan is on to the correct solution here -- [Array.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) is supported in node 6 and later, which includes [all currently-supported nodes](https://github.com/nodejs/Release).  Since I would prefer not to be in the business of supporting nodes the node foundation doesn't support, I've added an engines field to generate a warning to users of older nodes.  

Thanks for the thorough error report @mkitzman -- this one was easy to work on because of it.
